In [1]:
# Прізвище_пр_21.ipynb
# Імпортуємо необхідну бібліотеку
import numpy as np

# Завдання 1: Створіть одновимірний масив (вектор) зі значеннями натуральних чисел, починаючи з 1, та виведіть його значення.
vector = np.arange(1, 11)  # np.arange(1, 11) створює масив [1, 2, ..., 10]
print("Завдання 1: Вектор зі значеннями натуральних чисел від 1 до 10:")
print(vector)

# Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його косинусами кожного натурального числа, починаючи з 1, та виведіть його значення.
matrix_cos = np.cos(np.arange(1, 10).reshape(3, 3))
print("\nЗавдання 2: Матриця 3x3, заповнена косинусами натуральних чисел:")
print(matrix_cos)

# Завдання 3: Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -5 до 5 та виведіть непарні числа.
matrix_random_int = np.random.randint(-5, 6, (3, 3))
odd_numbers = matrix_random_int[matrix_random_int % 2 != 0]
print("\nЗавдання 3: Масив 3x3 з випадковими цілими числами від -5 до 5:")
print(matrix_random_int)
print("Непарні числа з масиву:")
print(odd_numbers)

# Завдання 4: Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від -0.7 до 0.7 та виведіть його значення.
matrix_random_float = np.random.uniform(-0.7, 0.7, (4, 4))
print("\nЗавдання 4: Масив 4x4 з випадковими дійсними числами від -0.7 до 0.7:")
print(matrix_random_float)

# Завдання 5: Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 10 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.
array1 = np.random.randint(10, 21, 5)
array2 = np.random.randint(10, 21, 5)
print("\nЗавдання 5: Два одновимірних масиви:")
print("Масив 1:", array1)
print("Масив 2:", array2)
print("Додавання:", array1 + array2)
print("Віднімання:", array1 - array2)
print("Множення:", array1 * array2)

# Завдання 6: Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.
matrix1 = np.random.randint(1, 11, (4, 4))
matrix2 = np.random.randint(1, 11, (4, 4))
matrix_product = np.dot(matrix1, matrix2)
print("\nЗавдання 6: Добуток двох матриць 4x4:")
print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(matrix_product)

# Завдання 7: Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.
matrix3 = np.random.randint(1, 6, (2, 3))
matrix4 = np.random.randint(1, 6, (3, 3))
matrix_multiplication = np.dot(matrix3, matrix4)
print("\nЗавдання 7: Добуток матриць 2x3 і 3x3:")
print("Матриця 2x3:")
print(matrix3)
print("Матриця 3x3:")
print(matrix4)
print("Добуток матриць:")
print(matrix_multiplication)

# Завдання 8: Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.
matrix5 = np.random.randint(1, 13, (2, 2))
matrix_inverse = np.linalg.inv(matrix5)
print("\nЗавдання 8: Обернена матриця 2x2:")
print("Матриця:")
print(matrix5)
print("Обернена матриця:")
print(matrix_inverse)

# Завдання 9: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix6 = np.random.uniform(0, 1, (3, 3))
matrix_transpose = matrix6.T
print("\nЗавдання 9: Транспонована матриця 3x3:")
print("Матриця:")
print(matrix6)
print("Транспонована матриця:")
print(matrix_transpose)

# Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
matrix7 = np.random.randint(1, 11, (3, 4))
vector2 = np.random.uniform(0, 1, (4, 1))
matrix_vector_product = np.dot(matrix7, vector2)
print("\nЗавдання 10: Добуток матриці 3x4 на вектор 4x1:")
print("Матриця:")
print(matrix7)
print("Вектор:")
print(vector2)
print("Добуток матриці на вектор:")
print(matrix_vector_product)

# Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
matrix8 = np.random.uniform(0, 1, (2, 3))
vector3 = np.random.randint(1, 11, (3, 1))
matrix_vector_product2 = np.dot(matrix8, vector3)
print("\nЗавдання 11: Добуток матриці 2x3 на вектор 3x1:")
print("Матриця:")
print(matrix8)
print("Вектор:")
print(vector3)
print("Добуток матриці на вектор:")
print(matrix_vector_product2)

# Завдання 12: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть суму всіх елементів першої матриці.
matrix9 = np.random.randint(1, 6, (3, 3))
matrix10 = np.random.randint(1, 6, (3, 3))
sum_matrix9 = np.sum(matrix9)
print("\nЗавдання 12: Сума елементів першої матриці 3x3:")
print("Матриця 1:")
print(matrix9)
print("Матриця 2:")
print(matrix10)
print("Сума всіх елементів першої матриці:", sum_matrix9)

# Завдання 13: Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть добуток їх елементів.
matrix11 = np.random.uniform(-2, 2, (4, 4))
matrix12 = np.random.uniform(-2, 2, (4, 4))
product_elements = np.multiply(matrix11, matrix12)
print("\nЗавдання 13: Добуток елементів двох матриць 4x4:")
print("Матриця 1:")
print(matrix11)
print("Матриця 2:")
print(matrix12)
print("Добуток елементів:")
print(product_elements)

# Завдання 14: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -10 до 10 та знайдіть найменший елемент матриці.
matrix13 = np.random.uniform(-10, 10, (3, 3))
min_element = np.min(matrix13)
print("\nЗавдання 14: Найменший елемент матриці 3x3:")
print("Матриця:")
print(matrix13)
print("Найменший елемент:", min_element)

# Завдання 15: Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці.
matrix14 = np.random.uniform(0, 1, (3, 3))
column_sums = np.sum(matrix14, axis=0).reshape(-1, 1)
print("\nЗавдання 15: Вектор-стовпчик з сумою елементів кожного стовпця:")
print("Матриця:")
print(matrix14)
print("Вектор-стовпчик:")
print(column_sums)

# Висновок
# У цій лабораторній роботі ми навчилися створювати та маніпулювати різними типами масивів і матриць у Python за допомогою бібліотеки NumPy, виконувати базові математичні операції, а також використовувати функції для роботи з лінійною алгеброю.


Завдання 1: Вектор зі значеннями натуральних чисел від 1 до 10:
[ 1  2  3  4  5  6  7  8  9 10]

Завдання 2: Матриця 3x3, заповнена косинусами натуральних чисел:
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]

Завдання 3: Масив 3x3 з випадковими цілими числами від -5 до 5:
[[-2 -2 -3]
 [ 5  5 -4]
 [-2 -1 -1]]
Непарні числа з масиву:
[-3  5  5 -1 -1]

Завдання 4: Масив 4x4 з випадковими дійсними числами від -0.7 до 0.7:
[[ 0.53263641  0.22566317 -0.16121276  0.49301207]
 [-0.08049254  0.12372228 -0.23138089  0.25774861]
 [-0.24316141 -0.15130864  0.3397321   0.05388137]
 [-0.42448641  0.66786639  0.33711481 -0.27229021]]

Завдання 5: Два одновимірних масиви:
Масив 1: [19 18 10 11 13]
Масив 2: [12 19 20 15 20]
Додавання: [31 37 30 26 33]
Віднімання: [  7  -1 -10  -4  -7]
Множення: [228 342 200 165 260]

Завдання 6: Добуток двох матриць 4x4:
Матриця 1:
[[9 5 5 5]
 [6 9 7 5]
 [7 7 3 7]
 [7 6 3 9]]
Матриця 2:
[[ 3  7  1 